
name: data

on:
  schedule:
    - cron: 0 0 * * *

  workflow_dispatch: {}

  push:
    paths:
      - .github/workflows/flat.yml

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Check out repo
        uses: actions/checkout@v2


      - name: Get current time
        run: |
          sda=`date -d "-7 days" +%Y-%m-%d`
          echo "::set-output name=DATE::$sda"
          echo "::set-output name=URLPATH::https://api.open.fec.gov/v1/filings/?per_page=100&sort=-receipt_date&sort_nulls_last=false&sort_hide_null=false&sort_null_only=false&min_receipt_date=$sda&api_key=DEMO_KEY"
        id: current-time

      - name: Use current time
        env:
          DAY: "${{ steps.current-time.outputs.DATE }}"
        run: echo $DATE

      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: "${{ steps.current-time.outputs.URLPATH }}"
          downloaded_filename: data.json
          postprocess: postprocess.ts
