
name: data

on:
  schedule:
    - cron: 0 0 * * *

  workflow_dispatch: {}

  push:
    paths:
      - .github/workflows/flat.yml

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Check out repo
        uses: actions/checkout@v2


      - name: Get current time
        uses: sblack4/get-current-time@master
        id: current-time
        with:
          format: YYYY-MM-DD
          days_offset: "-7"

      - name: Use current time
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          R_TIME: "${{ steps.current-time.outputs.readableTime }}"
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
          YEAR: "${{ steps.current-time.outputs.year }}"
          DAY: "${{ steps.current-time.outputs.day }}"
        run: echo $TIME $R_TIME $F_TIME $YEAR $DAY

      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: "https://api.open.fec.gov/v1/filings/?per_page=100&sort=-receipt_date&sort_nulls_last=false&sort_hide_null=false&page=1&sort_null_only=false&min_receipt_date=${{ steps.current-time.outputs.formattedTime }}&api_key=DEMO_KEY"
          downloaded_filename: data.json
          postprocess: postprocess.js
